### ISSUE TITLE
Test-TargetResource always failes non-English OS

### ISSUE THREAD

**Issue by Amedama96** [PowerShell/xDismFeature#11]
If you are using non english version of the Windows, Test-TargetResource always failes.

This issue caused by  [the code](https://github.com/PowerShell/xDismFeature/blob/3a9638a59bc07cfc126bf5704e9e5f39f575033a/DSCResources/MSFT_xDismFeature/MSFT_xDismFeature.psm1#L113)
``` Powershell
$DismGetFeatures = & dism.exe /Online /Get-Features
```

For fix this issue, Please add '/English' option.
``` Powershell
$DismGetFeatures = & dism.exe /Online /Get-Features /English
```

**Comment by mkht** [comment]
I met this issue too.
won't fix ?
